### ISSUE TITLE
Problem with submission.csv

### ISSUE THREAD

**Issue by ymittal23** [neptune-ml/open-solution-salt-identification#31]
There is problem with submission.csv file as kaggle is not accepting the file and showing error 

Evaluation Exception: Index was outside the bounds of the array.

There might be some problem with rle encoding

**Comment by jakubczakon** [comment]
@ymittal23 hmm that is interesting. 

I haven't had any problems so far. Did you manage to solve it yet?

**Comment by ymittal23** [comment]
No I tried multiple times but got same error. 
Evaluation Exception: Index was outside the bounds of the array.
I checked csv it looks fine to me. There are 18000 id for which prediction is done but when i am submitting result on kaggle it gives error

**Comment by jakubczakon** [comment]
I've just got that error (lucky me). 

Working on a fix but my guess is that it predicts the very last bottom right pixel and there is some evaluation bugs (as pointed out by Heng CherKeng).

**Comment by jakubczakon** [comment]
Ok, it seems that the problem was with the `run_lenght_encoding` function in the `utils.py`.
I dropped something that was there because of the DSB-2018 challenge it worked for me.

It is already on the newest master

**Comment by ymittal23** [comment]
Yeah I checked it now it is working fine. Thanks for the help.
