### ISSUE TITLE
No module named 'neptune'

### ISSUE THREAD

**Issue by qinhui99** [neptune-ml/open-solution-salt-identification#66]
Firstly I run "pip install -r requirements.txt". Then I try to run "python main.py", but got a error "No module named 'neptune'".  Did I miss something important ?

**Comment by jakubczakon** [comment]
Perheps you could upgrade `neptune-cli` with:

```bash
pip3 instsall neptune-cli --upgrade
```

**Comment by qinhui99** [comment]
It works.  Thanks.

**Comment by harshsinghiitd** [comment]
Collecting pycocotools==2.0.0 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/96/84/9a07b1095fd8555ba3f3d519517c8743c2554a245f9476e5e39869f948d2/pycocotools-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HARSHS~1\AppData\Local\Temp\pip-install-rai_iub0\pycocotools\setup.py", line 2, in <module>
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'

-------------------------------------------------------------------------------------------------------------------
Please tell how to reslove this
